language:
  python

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-report term --cov=tests/

env:
  - CODECOV_TOKEN=1dd387c2-ef8b-43f8-8bed-f5483f8d759a

after_success:
  - codecov